name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/forum-api
            git pull origin main
            /home/ubuntu/.nvm/versions/node/v18.12.1/bin/node /home/ubuntu/.nvm/versions/node/v18.12.1/bin/pnpm install
            /home/ubuntu/.nvm/versions/node/v18.12.1/bin/node /home/ubuntu/.nvm/versions/node/v18.12.1/bin/pnpm migrate up
            /home/ubuntu/.local/share/pnpm/pm2 restart forum-api
